backend:
  name: git-gateway

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "/img/"

collections:
  - name: docs
    label: "docs"
    folder: docs
    identifier_field: title
    extension: md
    widget: "list"
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown }
